# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  #NUGET_PACKAGES: /mnt/a/1/.nuget/packages

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    packagesDirectory: $(Pipeline.Workspace)/.nuget/packages
  displayName: 'dotnet restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
  displayName: 'dotnet build $(buildConfiguration)'

- script: ls -l $(Pipeline.Workspace)/.nuget/packages
